name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable # Use the stable Flutter channel

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Build the Flutter web app
      - name: Build web
        run: flutter build web

      # Step 5: Debug PAT
      - name: Debug PAT
        run: |
          if [ -z "${{ secrets.PAT }}" ]; then
            echo "PAT secret is not set or accessible."
          else
            echo "PAT secret is accessible."
          fi

      # Step 6: Deploy to GitHub Pages (main branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./build/web
          destination_dir: ./ # Deploy to the root of the main branch
          keep_files: false # Overwrite existing files in the main branch
